config/routes.rb
Rails.application.routes.draw do
  #作ったコントローラを呼び出す
  devise_for :users, :controllers =>{ 
       :registrations => 'users/registrations',
       :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :destroy, :update]
  resources :goods, only: [:index, :show]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :create, :show, :destroy, :new]

  get "/" => "home#top"
  get "home/finish" => "home#finish"
  get "home/done" => "home#done"


  
  
  get "admin/users" => "users#admin"
  get "admin/" => "users#admin_index"
  get "admin/users/:id" => "users#admin_show", as: "show_admin_user"
  delete "admin/users/:id" => "users#admin_destroy", as: "destroy_admin_user"
  get "admin/users/:id/edit" => "users#admin_edit", as: "edit_admin_user"
  patch "admin/users/:id" => "users#admin_update", as: "update_admin_user"

  get "admin/goods/" => "goods#admin_index"
  get "admin/goods/new" => "goods#admin_new"
  post "search" => "goods#search"
  get "admin/goods/:id" => "goods#admin_show", as: "show_admin_good"
  get "admin/goods/:id/edit" => "goods#admin_edit", as: "edit_admin_good"
  post "admin/goods/" => "goods#admin_create", as: "create_admin_good"
  delete "admin/goods/:id" => "goods#admin_destroy", as: "destroy_admin_good"
  patch "admin/goods/:id" => "goods#admin_update", as: "update_admin_good"

  get "admin/orders/:id/edit" => "orders#admin_edit", as: "edit_admin_order"
  patch "admin/orders/:id" => "orders#admin_update", as: "update_admin_order"

=begin
Prefix Verb   URI Pattern                                                                              Controller#Action
         new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
             user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
     destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
        new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
       edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
            user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
                          PUT    /users/password(.:format)                                                                devise/passwords#update
                          POST   /users/password(.:format)                                                                devise/passwords#create
 cancel_user_registration GET    /users/cancel(.:format)                                                                  users/registrations#cancel
    new_user_registration GET    /users/sign_up(.:format)                                                                 users/registrations#new
   edit_user_registration GET    /users/edit(.:format)                                                                    users/registrations#edit
        user_registration PATCH  /users(.:format)                                                                         users/registrations#update
                          PUT    /users(.:format)                                                                         users/registrations#update
                          DELETE /users(.:format)                                                                         users/registrations#destroy
                          POST   /users(.:format)                                                                         users/registrations#create
                edit_user GET    /users/:id/edit(.:format)                                                                users#edit
                     user GET    /users/:id(.:format)                                                                     users#show
                          PATCH  /users/:id(.:format)                                                                     users#update
                          PUT    /users/:id(.:format)                                                                     users#update
                          DELETE /users/:id(.:format)                                                                     users#destroy
                    goods GET    /goods(.:format)                                                                         goods#index
                     good GET    /goods/:id(.:format)                                                                     goods#show
                    carts GET    /carts(.:format)                                                                         carts#index
                          POST   /carts(.:format)                                                                         carts#create
                     cart PATCH  /carts/:id(.:format)                                                                     carts#update
                          PUT    /carts/:id(.:format)                                                                     carts#update
                          DELETE /carts/:id(.:format)                                                                     carts#destroy
                   orders GET    /orders(.:format)                                                                        orders#index
                          POST   /orders(.:format)                                                                        orders#create
                new_order GET    /orders/new(.:format)                                                                    orders#new
                    order GET    /orders/:id(.:format)                                                                    orders#show
                          DELETE /orders/:id(.:format)                                                                    orders#destroy
                          GET    /                                                                                        home#top
                home_done GET    /home/done(.:format)                                                                     home#done
              admin_users GET    /admin/users(.:format)                                                                   users#admin
                    admin GET    /admin(.:format)                                                                         users#admin_index
          show_admin_user GET    /admin/users/:id(.:format)                                                               users#admin_show
       destroy_admin_user DELETE /admin/users/:id(.:format)                                                               users#admin_destroy
          edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          users#admin_edit
        update_admin_user PATCH  /admin/users/:id(.:format)                                                               users#admin_update
              admin_goods GET    /admin/goods(.:format)                                                                   goods#admin_index
          admin_goods_new GET    /admin/goods/new(.:format)                                                               goods#admin_new
                   search POST   /search(.:format)                                                                        goods#search
          show_admin_good GET    /admin/goods/:id(.:format)                                                               goods#admin_show
          edit_admin_good GET    /admin/goods/:id/edit(.:format)                                                          goods#admin_edit
        create_admin_good POST   /admin/goods(.:format)                                                                   goods#admin_create
       destroy_admin_good DELETE /admin/goods/:id(.:format)                                                               goods#admin_destroy
        update_admin_good PATCH  /admin/goods/:id(.:format)                                                               goods#admin_update
         edit_admin_order GET    /admin/orders/:id/edit(.:format)                                                         orders#admin_edit
       update_admin_order PATCH  /admin/orders/:id(.:format)                                                              orders#admin_update
               refile_app        /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
       rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
=end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #モデル指定
  has_many :users_children
  has_many :carts
  has_many :orders
  #親から子のモデルをいじるとき作成する
  accepts_nested_attributes_for :users_children, :carts, :orders

  validates :phone_number, presence: true, length: { in: 8..11 }, format: { with: /\A[0-9]+\Z/ }





end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  def new
    @user = User.new
    @user.users_children.build
  end

  def create
    super
    user = User.new(configure_sign_up_params)
    user.save
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :admin_flag_check?, only: [:admin, :admin_index, :admin_show, :admin_destroy, :admin_update, :admin_edit]
  before_action :resignation_flag_check?, only: [:show, :edit, :destroy, :update, :admin, :admin_index, :admin_show, :admin_destroy, :admin_edit, :admin_update]

  def show
    @user = current_user
    @orders = Order.where(user_id: @user.id)
    orders = Order.find_by(user_id: @user.id)

    # ユーザーの購入履歴があるとき
    if orders != nil

      # viewで使う、購入履歴を表示するか判断するフラグを作成
      @buy_view_flg = 1

    # ユーザーの購入履歴がないとき(nil)
    else

      # viewで使う、購入履歴を表示するか判断するフラグを作成
      @buy_view_flg = 0
      
    end

    

  end

  def edit
    @user = current_user
  end

  def destroy
    @user = User.find(params[:id])
    @user.resignation_flag = 1
    @user.save
    redirect_to "/"
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      #パスワード変更するとログアウトしてしまうので、もう一度強制的にサインインさせてる。
      sign_in(@user, bypass: true)
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def admin
    # idが古い順（最新順）に並び替える
    @order = Order.where(buy_flag: 1).order(:id).reverse_order
    
  end

  def admin_index
    @users = User.all
    @children = UsersChild.all
    @temp_array = Array.new
  end

  def admin_show
    @user = User.find(params[:id])
    @child = UsersChild.find_by(user_id: params[:id])
    @orders = Order.where(user_id: @user.id)
  end

  def admin_destroy
     @user = User.find(params[:id])
     @user.resignation_flag = 1
     @user.save
     redirect_to admin_path
  end

  def admin_edit
    @user = User.find(params[:id])
    @users_children = UsersChild.find_by(user_id: @user.id)
  end

  def admin_update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to admin_path
    else
      render "admin_edit"
    end
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :phone_number, users_children_attributes:[:id, :name_kanji_mei, :name_kanji_sei, :name_kana_mei, :name_kana_sei, :post_code, :address] )
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin.html.erb
_<div class="container">
	<button class="btn btn-primary btn-block">アルプスレコード（管理者ページ）</button>
	<br>
	<div class="row justify-content-around">
		<%= link_to "商品一覧", admin_goods_path, class: "btn btn-warning" %>
		<%= link_to "ユーザー一覧", admin_path, class: "btn btn-info" %>
		<%= link_to "商品を追加", admin_goods_new_path, class: "btn btn-danger" %>
	</div>
	<br>
	<br>
</div>

<!-- 購入履歴表示部分 -->
<div class="container">
	<div class="row">
		<div class="col-12">
			<h1 class="text-center">購入履歴</h1>
			<br>
			<table class="table table-bordered">
			<!-- table-striped:ボーダー設定 -->

				<colgroup span="1" width="10%"></colgroup>
				<colgroup span="1" width="12%"></colgroup>
				<colgroup span="1" width="38%"></colgroup>
				<colgroup span="1" width="20%"></colgroup>
				<colgroup span="1" width="10%"></colgroup>
				<colgroup span="1" width="10%"></colgroup>

				<thead>
			        <tr>
			        	<!-- 文字数で勝手にテーブルサイズが変更される対応 -->
			        		<th class="text-center">購入者</th>
			        		<th class="text-center">購入日</th>
			        		<th class="text-center">購入内容</th>
			        		<th class="text-center">送付先</th>
			        		<th class="text-center">送付先氏名</th>
			        		<th class="text-center">ステータス</th>
			        	<!-- text-center:中央揃え -->
			        </tr>
			    </thead>
			    <tbody>
			    	<% @order.each do |order| %>
						<tr>
							<!-- 1.購入者 -->
							<td class="text-center"><%= order.user.users_children[0].name_kanji_sei + order.user.users_children[0].name_kanji_mei %></td>

							<!-- 2.購入日 -->
							<td class="text-center small"><%= order.created_at.strftime("%Y-%m-%d") %> </td>

							<!-- 3.購入内容 -->
							<td>
								<% order.orders_children.each do |order_child|  %>

									<!-- 購入内容を2分割にする。 -->
									<div class="row">
										<div class="col-md-6">
											<!-- small:文字のサイズを75％ -->
											<!-- text-right:右揃え -->
											<p class="small text-right">シングル/アルバム名:</p>
											<p class="small text-right">価格:</p>
											<p class="small text-right">購入枚数:</p>
											<p class="small text-right">小計:</p>
										</div>
										<div class="col-md-6">
											<!-- text-center:中央揃え -->
											<p class="small text-center"><%= order_child.good.goods_title %></p>
											<p class="small text-center">¥<%= order_child.good.price %>円</p>
											<p class="small text-center"><%= order_child.order_value %>枚</p>
											<p class="small text-center">¥<%= order_child.good.price * order_child.order_value %>円</p>
										</div>
									</div>

								<% end %>
							</td>

							<!-- 4.送付先 -->
							<td class="text-center">
								<!-- 送付先が手入力の場合-->
								<% if order.delivery_select_flag == 0 %>
									<p class="small text-center">〒<%= order.other_post_code.chars[0] + order.other_post_code.chars[1] + order.other_post_code.chars[2] + "-" + order.other_post_code.chars[3] + order.other_post_code.chars[4] + order.other_post_code.chars[5] + order.other_post_code.chars[6] %></p>
			            			<p class="small text-center"><%= order.other_address %></p>
								<!-- 送付先が登録された情報の場合 -->
								<% else %>
									<p class="small text-center">〒<%= order.user.users_children[0].post_code.chars[0] + order.user.users_children[0].post_code.chars[1] + order.user.users_children[0].post_code.chars[2] + "-" + order.user.users_children[0].post_code.chars[3] + order.user.users_children[0].post_code.chars[4] + order.user.users_children[0].post_code.chars[5] + order.user.users_children[0].post_code.chars[6] %></p>
			            			<p class="small text-center"><%= order.user.users_children[0].address %></p>
								<% end %>
							</td>

							<!-- 5.送付先氏名 -->
							<td class="text-center">
								<!-- 送付先が手入力の場合-->
								<% if order.delivery_select_flag == 0 %>
									<%= order.other_name %>
								<!-- 送付先が登録された情報の場合 -->
								<% else %>
									<%= order.user.users_children[0].name_kanji_sei + order.user.users_children[0].name_kanji_mei %>
								<% end %>
							</td>

							<!-- 6.配送ステータス -->
							<td class="text-center">
								<!-- 出荷済みの場合 -->
								<% if order.delivery_status == 2 %>
									<%= link_to "出荷済み", edit_admin_order_path(order.id) %>
								<!-- 準備中の場合 -->
								<% elsif order.delivery_status == 1 %>
									<%= link_to "準備中", edit_admin_order_path(order.id) %>
								<!-- 受付の場合 -->
								<% else %>
									<%= link_to "受付", edit_admin_order_path(order.id) %>
								<% end %>
							</td>

						</tr>

					<% end %>
			    	
			    </tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/admin_edit.html.erb
<h1>編集</h1>
<%= form_for @user, url: update_admin_user_path(@user.id) do |f| %>
  

  <%= f.fields_for :users_children do |child| %>

    <h4>名前（性）</h4>
    <div class="field">
        <%= child.label :name_kanji_sei %><br />
        <%= child.text_field :name_kanji_sei, autofocus: true, autocomplete: "name_kanji_sei" %>
    </div>

    <h4>名前（名）</h4>
    <div class="field">
        <%= child.label :name_kanji_mei %><br />
        <%= child.text_field :name_kanji_mei, autofocus: true, autocomplete: "name_kanji_mei" %>
    </div>

    <h4>名前（カナ性）</h4>
    <div class="field">
        <%= child.label :name_kana_sei %><br />
        <%= child.text_field :name_kana_sei, autofocus: true, autocomplete: "name_kana_sei" %>
    </div>

    <h4>名前（カナ名）</h4>
    <div class="field">
        <%= child.label :name_kana_mei %><br />
        <%= child.text_field :name_kana_mei, autofocus: true, autocomplete: "name_kana_mei" %>
    </div>

    <h4>郵便番号</h4>
    <div class="field">
        <%= child.label :post_code %><br />
        <%= child.text_field :post_code, autofocus: true, autocomplete: "post_code", maxlength: '7' %>
    </div>

    <h4>住所</h4>
    <div class="field">
        <%= child.label :address %><br />
        <%= child.text_field :address, autofocus: true, autocomplete: "address" %>
    </div>
  <% end %>

    <h4>電話番号</h4>
    <div class="field">
        <%= f.label :phone_number %><br />
        <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number" %>
    </div>

    <h4>メールアドレス</h4>
    <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
    <%= f.submit '更新' %>

<% end %>

app/views/users/admin_index.html.erb
<div class="title">
	<h1>ユーザー一覧</h1>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<table class="table">

					<colgroup span="1" style="width:10%;">
					<colgroup span="2" style="width:10%;">
					<colgroup span="1" style="width:40%;">
					<colgroup span="1" style="width:20%;">
					<colgroup span="1" style="width:10%;">

				<thead>
						<th>ID</th>
						<th>名前</th>
						<th>郵便番号</th>
						<th>住所</th>
						<th>e-mail</th>
						<th>退会状態</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>

				</thead>

			<% @children.each do |child| %>
				<tbody>
					<!-- 複数の子供がいた場合は、先頭だけもってくる -->
					<% if @temp_array.include?(child.user_id)  %>

					<% else %>

						<td><%= child.user.id %></td>
						<td><%= link_to child.name_kanji_sei + child.name_kanji_mei, show_admin_user_path(child.user_id) %></td>
						<td>〒<%= child.post_code.chars[0] + child.post_code.chars[1] + child.post_code.chars[2] + "-" + child.post_code.chars[3] + child.post_code.chars[4] + child.post_code.chars[5] + child.post_code.chars[6] %></td>
						<td><%= child.address %></td>
						<td><%= child.user.email %></td>

						<% if child.user.resignation_flag == 1 %>
							<td style="color: red;">退会</td>
						<% else %>
							<td></td>
						<% end %>


						<% @temp_array.push(child.user_id) %>
					<% end %>

					<!-- 余白調整用です。消さないで -->
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<!-- ここまで -->

				</tbody>
			<% end %>

			</table>
		</div>

 			<%= link_to "戻る", admin_users_path, class: "btn btn-primary mx-auto" %>

	</div>
</div>

app/views/users/admin_show.html.erb
<div class="title">
	<h1>ユーザー詳細</h1>
</div>

<div class="d-flex justify-content-end">
	<div class="m-2">
			<%= link_to "編集", edit_admin_user_path(@user.id), class: "btn btn-primary" %>
	</div>

	<div class="m-2">
			<%= link_to "削除", destroy_admin_user_path(@user.id),method: :delete,class: "btn btn-primary .m-auot"  %>
	</div>

	<div class="m-2">
			<%= link_to "戻る", admin_path, class: "btn btn-primary .m-auto" %>
	</div>
</div>

<!-- ユーザー情報 -->
  	<br>
  	<table class="table table-bordered">

  		<colgroup span="1" width="20%"></colgroup>
  		<colgroup span="1" width="80%"></colgroup>

  		<thead>
  		</thead>
  		
  		<tbody>
  			<tr align="center">
  				<td>名前</td>
  				<td><%= @child.name_kanji_sei + @child.name_kanji_mei %></td>
  			</tr>
  			<tr align="center">
  				<td>名前（カナ）</td>
  				<td><%= @child.name_kana_sei + @child.name_kana_mei %></td>
  			</tr>
  			<tr align="center">
  				<td>郵便番号</td>
  				<td>〒<%= @child.post_code.chars[0] + @child.post_code.chars[1] + @child.post_code.chars[2] + "-" + @child.post_code.chars[3] + @child.post_code.chars[4] + @child.post_code.chars[5] + @child.post_code.chars[6] %></td>
  			</tr>
  			<tr align="center">
  				<td>住所</td>
  				<td><%= @child.address %></td>
  			</tr>
  			<tr align="center">
  				<td>メールアドレス</td>
  				<td><%= @child.user.email %></td>
  			</tr>
  			
  		</tbody>
  	</table>
  </div>
</body>

  	<!-- 購入情報 -->
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="my-3">
				<h1 class="text-center">購入履歴</h1>
			</div>
			<br>
			<table class="table table-bordered">
			<!-- table-striped:ボーダー設定 -->

				<colgroup span="1" width="10%"></colgroup>
				<colgroup span="1" width="12%"></colgroup>
				<colgroup span="1" width="38%"></colgroup>
				<colgroup span="1" width="20%"></colgroup>
				<colgroup span="1" width="10%"></colgroup>
				<colgroup span="1" width="10%"></colgroup>

			    <thead>
			        <tr>
			        	<!-- 文字数で勝手にテーブルサイズが変更される対応 -->
			        		<th class="text-center">購入者</th>
			        		<th class="text-center">購入日</th>
			        		<th class="text-center">購入内容</th>
			        		<th class="text-center">送付先</th>
			        		<th class="text-center">送付先氏名</th>
			        		<th class="text-center">ステータス</th>
			        	<!-- text-center:中央揃え -->
			        </tr>
			    </thead>
			    <tbody>

					<% @orders.each do |order| %>
						<tr>
							<!-- 1.購入者 -->
							<td class="text-center"><%= order.user.users_children[0].name_kanji_sei + order.user.users_children[0].name_kanji_mei %></td>

							<!-- 2.購入日 -->
							<td class="text-center small"><%= order.created_at.strftime("%Y-%m-%d") %></td>

							<!-- 3.購入内容 -->
							<td>
								<% order.orders_children.each do |order_child| %>

									<!-- 購入内容を2分割にする。 -->
							        	<div class="row">
							        		<div class="col-md-6">
							        			<!-- small:文字のサイズを75％ -->
							        			<!-- text-right:右揃え -->
							        			<p class="small text-right">シングル/アルバム名:</p>
								            	<p class="small text-right">価格:</p>
								            	<p class="small text-right">購入枚数:</p>
								            	<p class="small text-right">小計:</p>
							        		</div>
							        		<div class="col-md-6">
							        			<!-- text-center:中央揃え -->
							        			<p class="small text-center"><%= order_child.good.goods_title %></p>
								            	<p class="small text-center">¥<%= order_child.good.price %>円</p>
								            	<p class="small text-center"><%= order_child.order_value %>枚</p>
								            	<p class="small text-center">¥<%= order_child.good.price * order_child.order_value %>円</p>
							        		</div>
							        	</div>
									
								<% end %>
							</td>

							<!-- 4.送付先 5.送付先氏名 -->
							<!-- 登録された住所か、手入力された住所かを分岐する。 -->
							<!-- 手入力 -->
							<% if order.delivery_select_flag == 0 %>

								<!-- 4.送付先 -->
								<td>
									<!-- slice:(0..2) 1文字目〜3文字目を取り出す -->
									<p class="small text-center">〒<%= order.other_post_code.slice(0..2) + "-" + order.other_post_code.slice(3..6) %></p>
									<p class="small text-center"><%= order.other_address %></p>
								</td>

								<!-- 5.送付先氏名 -->
								<td class="text-center"><%= order.other_name %></td>

							<!-- 登録済みの住所 -->
							<% else %>

								<!-- 4.送付先 -->
								<td>
									<p class="small text-center">〒<%= order.user.users_children[0].post_code.slice(0..2) + "-" + order.user.users_children[0].post_code.slice(3..6) %></p>
									<p class="small text-center"><%= @child.address %></p>
								</td>

								<!-- 5.送付先氏名 -->
								<td class="text-center"><%= @child.name_kanji_sei + @child.name_kanji_mei %></td>


							<% end %>

							<!-- 6.出荷ステータス -->
							<td class="text-center">
								<% if order.delivery_status == 2 %>
									<%= link_to " 出荷済み", edit_admin_order_path(order.id) %>
								<% elsif order.delivery_status == 1 %>
									<%= link_to " 準備中", edit_admin_order_path(order.id) %>
								<% else %>
									<%= link_to " 受付中", edit_admin_order_path(order.id) %>
								<% end %>
					        </td>
						</tr>
					<% end %>

			    </tbody>
			</table>
		</div>
	</div>
</div>