config/routes.rb
Rails.application.routes.draw do
  #作ったコントローラを呼び出す
  devise_for :users, :controllers =>{ 
       :registrations => 'users/registrations',
       :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :destroy, :update]
  resources :goods, only: [:index, :show]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :create, :show, :destroy, :new]

  get "/" => "home#top"
  get "home/finish" => "home#finish"
  get "home/done" => "home#done"


  
  
  get "admin/users" => "users#admin"
  get "admin/" => "users#admin_index"
  get "admin/users/:id" => "users#admin_show", as: "show_admin_user"
  delete "admin/users/:id" => "users#admin_destroy", as: "destroy_admin_user"
  get "admin/users/:id/edit" => "users#admin_edit", as: "edit_admin_user"
  patch "admin/users/:id" => "users#admin_update", as: "update_admin_user"

  get "admin/goods/" => "goods#admin_index"
  get "admin/goods/new" => "goods#admin_new"
  post "search" => "goods#search"
  get "admin/goods/:id" => "goods#admin_show", as: "show_admin_good"
  get "admin/goods/:id/edit" => "goods#admin_edit", as: "edit_admin_good"
  post "admin/goods/" => "goods#admin_create", as: "create_admin_good"
  delete "admin/goods/:id" => "goods#admin_destroy", as: "destroy_admin_good"
  patch "admin/goods/:id" => "goods#admin_update", as: "update_admin_good"

  get "admin/orders/:id/edit" => "orders#admin_edit", as: "edit_admin_order"
  patch "admin/orders/:id" => "orders#admin_update", as: "update_admin_order"

=begin
Prefix Verb   URI Pattern                                                                              Controller#Action
         new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
             user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
     destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
        new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
       edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
            user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
                          PUT    /users/password(.:format)                                                                devise/passwords#update
                          POST   /users/password(.:format)                                                                devise/passwords#create
 cancel_user_registration GET    /users/cancel(.:format)                                                                  users/registrations#cancel
    new_user_registration GET    /users/sign_up(.:format)                                                                 users/registrations#new
   edit_user_registration GET    /users/edit(.:format)                                                                    users/registrations#edit
        user_registration PATCH  /users(.:format)                                                                         users/registrations#update
                          PUT    /users(.:format)                                                                         users/registrations#update
                          DELETE /users(.:format)                                                                         users/registrations#destroy
                          POST   /users(.:format)                                                                         users/registrations#create
                edit_user GET    /users/:id/edit(.:format)                                                                users#edit
                     user GET    /users/:id(.:format)                                                                     users#show
                          PATCH  /users/:id(.:format)                                                                     users#update
                          PUT    /users/:id(.:format)                                                                     users#update
                          DELETE /users/:id(.:format)                                                                     users#destroy
                    goods GET    /goods(.:format)                                                                         goods#index
                     good GET    /goods/:id(.:format)                                                                     goods#show
                    carts GET    /carts(.:format)                                                                         carts#index
                          POST   /carts(.:format)                                                                         carts#create
                     cart PATCH  /carts/:id(.:format)                                                                     carts#update
                          PUT    /carts/:id(.:format)                                                                     carts#update
                          DELETE /carts/:id(.:format)                                                                     carts#destroy
                   orders GET    /orders(.:format)                                                                        orders#index
                          POST   /orders(.:format)                                                                        orders#create
                new_order GET    /orders/new(.:format)                                                                    orders#new
                    order GET    /orders/:id(.:format)                                                                    orders#show
                          DELETE /orders/:id(.:format)                                                                    orders#destroy
                          GET    /                                                                                        home#top
                home_done GET    /home/done(.:format)                                                                     home#done
              admin_users GET    /admin/users(.:format)                                                                   users#admin
                    admin GET    /admin(.:format)                                                                         users#admin_index
          show_admin_user GET    /admin/users/:id(.:format)                                                               users#admin_show
       destroy_admin_user DELETE /admin/users/:id(.:format)                                                               users#admin_destroy
          edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          users#admin_edit
        update_admin_user PATCH  /admin/users/:id(.:format)                                                               users#admin_update
              admin_goods GET    /admin/goods(.:format)                                                                   goods#admin_index
          admin_goods_new GET    /admin/goods/new(.:format)                                                               goods#admin_new
                   search POST   /search(.:format)                                                                        goods#search
          show_admin_good GET    /admin/goods/:id(.:format)                                                               goods#admin_show
          edit_admin_good GET    /admin/goods/:id/edit(.:format)                                                          goods#admin_edit
        create_admin_good POST   /admin/goods(.:format)                                                                   goods#admin_create
       destroy_admin_good DELETE /admin/goods/:id(.:format)                                                               goods#admin_destroy
        update_admin_good PATCH  /admin/goods/:id(.:format)                                                               goods#admin_update
         edit_admin_order GET    /admin/orders/:id/edit(.:format)                                                         orders#admin_edit
       update_admin_order PATCH  /admin/orders/:id(.:format)                                                              orders#admin_update
               refile_app        /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
       rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
=end

end

app/models/order.rb
class Order < ApplicationRecord

	# rails5から、requiredオプションが標準でtrueになります。
	# なので、標準では関連先のオブジェクトを検査しにいきます。
	# Createメゾット内に@userモデルが存在しないので、エラーになります。
	# 以下のオプションを
	# oprional:true 関連先のオブジェクトが存在するかを検証しない
	belongs_to :user, optional: true
	has_many :orders_children

	#親から子のモデルをいじるとき作成する
  	accepts_nested_attributes_for :orders_children

  	validates :payment_method, presence: true
  	validates :delivery_select_flag, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :resignation_flag_check?
  before_action :admin_flag_check?, only: [:admin_update, :admin_edit]

  def index
    @cart = Cart.find_by(user_id: current_user.id)
      if @cart == nil
        redirect_to carts_path
      else
        @order = Order.new
        @user = current_user
        @user_children = UsersChild.where(user_id: @user.id)
      end
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id

    if @order.delivery_select_flag == 0
      @order.save
      redirect_to order_path(@order.user_id)
    else
      @order.save
      redirect_to order_path(@order.id)
    end

  end

  def show
    @user = current_user
    @carts = @user.carts
    @orders = Order.find_by(user_id: @user.id, buy_flag: nil)
    @delivery_price = DeliveryPrice.find(1).delivery_price


    # 
    # 現在時刻の取得ロジック 始まり
    #

    # 現在時刻の取得
    time_now = DateTime.now
    # 現在時刻を日本時刻に変換
    time_now_tokyo = time_now.in_time_zone('Tokyo')
    # 送料テーブルを一旦全部持ってくる
    delivery_price_all = DeliveryPrice.all

    # # 送料テーブルをeach文で回す
    target_delivery_price = 0
    # 下記メゾットを動かすためには、以下の手順を実装する。
    # 1.delivery_start_day、delivery_finish_dayにとりあえず、created_atの値を代入
    # 2.delivery_price.delivery_finish_day = delivery_price.delivery_finish_day + 100000000
    #  とか書いてみる +10000000秒加算されるはず
    # 3.saveする。
    delivery_price_all.each do |delivery_price|

      # 現在時刻が、送料適用開始日を過ぎているか
      if time_now_tokyo > delivery_price.delivery_start_day.in_time_zone('Tokyo')
        # 現在時刻が、送料適用終了日を過ぎていないか
        if time_now_tokyo < delivery_price.delivery_finish_day.in_time_zone('Tokyo')
          target_delivery_price = delivery_price.delivery_price
        else
          # 処理しません
        end
      else
        # 処理しません
      end

    end
    #
    # 現在時刻の取得ロジック 終わり
    #


    # 
    # 消費税の取得ロジック 始まり
    #

    # 消費税テーブルを一旦全部持ってくる
    tax_all = Tax.all

    # # 送料テーブルをeach文で回す
    target_tax = 0

    tax_all.each do |tax|

      # 現在時刻が、消費税適用開始日を過ぎているか
      if time_now_tokyo > tax.tax_start_day.in_time_zone('Tokyo')
        # 現在時刻が、送料適用終了日を過ぎていないか
        if time_now_tokyo < tax.tax_finish_day.in_time_zone('Tokyo')
          target_tax = tax.tax
        else
          # 処理しません
        end
      else
        # 処理しません
      end

    end
    #
    # 消費税の取得ロジック 終わり
    #



    # 小計金額の定義
    @price = 0
    @carts.each do |cart|
      @price = @price + (cart.good.price*cart.cart_value)
    end

    # 消費税の定義
    @tax = (@price + target_delivery_price) * target_tax - (@price + target_delivery_price)

    # 総計金額の定義
    @total_price = @price + target_delivery_price + @tax

    # delivery_select_flagの値により、表示する住所を変える
    # delivery_select_flag == 0 :手入力
    # delivery_select_flag == 1 :登録住所から
    if @orders.delivery_select_flag == 0
      @post_code = @orders.other_post_code
      @address = @orders.other_address
    else
      @post_code = @user.users_children[0].post_code
      @address = @user.users_children[0].address
    end

  end

  def destroy
    @order = Order.find(params[:id])
   
    @carts = Cart.where(user_id: current_user.id)
    @carts.destroy_all
    @order.destroy
    redirect_to goods_path
  end

  def new
  end

  def admin_edit
    @order = Order.find(params[:id])
  end

  def admin_update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_users_path
  end

  private

  def order_params
     params.require(:order).permit(:id, :delivery_status, :other_address, :payment_method, :other_name, :other_kana, :other_post_code, :delivery_select_flag, users_child_attributes: [:post_code, :address])
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/admin_edit.html.erb
<div class="main-visual" style="margin: 50px;">
  <div class="a" style="text-align: center;">
	<h2>配送状況変更</h2>
  </div>
</div>

<main clss="main" style="margin-top: 100px;">
	
	<div class="" style="text-align: center;">
		<div class="" style="margin: 150px 0 20px 0;">
			<%= form_for @order, url: update_admin_order_path(@order.id) do |f| %>
			
			<div class="form-check p-3 mb-2 bg-info text-white rounded">
			<label>
				<%= f.radio_button :delivery_status,0, class: "form-check-input" %>受付
			</label>
			</div>
			<div class="form-check p-3 mb-2 bg-info text-white rounded">
			<label>
				<%= f.radio_button :delivery_status,1, class: "form-check-input" %>準備中
			</label>
			</div>
			<div class="form-check p-3 mb-2 bg-info text-white rounded">
			<label>
				<%= f.radio_button :delivery_status,2, class: "form-check-input" %>出荷完了
			</label>
			</div>
			
		<%= f.submit "更新", class: "btn btn-info" %>
		 		 
		<% end %>
	</div>
	<div class="container" style="text-align: center;">


			<div class="" style="margin: 30px;">
	 		</div>
	 		<div class="" style="margin: 50px;">
		 		<%= link_to "戻る", show_admin_user_path(@order.user.id), class: "btn btn-primary" %>
	 		</div>

 	</div>
</main>

app/views/orders/index.html.erb
<div class="container">
	<%= form_for @order do |f| %>

		<!-- お支払い方法部分 -->
		<h1>お支払い方法</h1>
		<div class="card">
			<div class="card-body">

				<div class="form-check p-3 mb-2 bg-primary text-white rounded">
					<!-- レイアウト崩れたため、aタグで無理やり設定してます。 -->
					<a>　</a>
				<label>
					<%= f.radio_button :payment_method, 0,class: "form-check-input" %>銀行振込
				</label>
				</div>
				<div class="form-check p-3 mb-2 bg-warning text-white rounded">
					<!-- レイアウト崩れたため、aタグで無理やり設定してます。 -->
					<a>　</a>
				<label>
					<%= f.radio_button :payment_method, 1,class: "form-check-input" %>クレジットカード
				</label>
				</div>
				<div class="form-check p-3 mb-2 bg-info text-white rounded">
					<!-- レイアウト崩れたため、aタグで無理やり設定してます。 -->
					<a>　</a>
				<label>
					<%= f.radio_button :payment_method, 2,class: "form-check-input" %>代金引換
				</label>
				</div>


			</div>
		</div>
		<br>


		<!-- 配送先選択部分 -->
		<h1>配送先選択</h1>
		<div class="card">
			<div class="card-body">

				<div class="form-check p-3 mb-2 bg-secondary text-white rounded">
					<!-- レイアウト崩れたため、aタグで無理やり設定してます。 -->
					<a>　</a>
				<% @user_children.each do |child| %>
					<label>
						<%= f.radio_button :delivery_select_flag, 1, class: "form-check-input" %>
						<p>〒<%= child.post_code.chars[0] + child.post_code.chars[1] + child.post_code.chars[2] + "-" + child.post_code.chars[3] + child.post_code.chars[4] + child.post_code.chars[5] + child.post_code.chars[6] %></p>
						<p><%= child.address %></p>
					</label>
				<% end %>
				</div>

				<div class="form-check p-3 mb-2 bg-secondary text-white rounded">
						<!-- レイアウト崩れたため、aタグで無理やり設定してます。 -->
						<a>　</a>
					<label>

						<%= f.radio_button :delivery_select_flag, 0, class: "form-check-input" %>
						<div class="d-flex justify-content-center">
							<p>上記以外の配送先をご希望のお客様は、左のボタンをクリックしていただき、<br>
							下記の記入欄に、お届け先のお名前、住所、郵便番号（ハイフン付き）をご記入ください。</p>
						</div>

						<label for="text3">名前（漢字）:</label>
						<%= f.text_field :other_name, class: "form-control" %>

						<label for="text3">名前（カナ）:</label>
						<%= f.text_field :other_kana, class: "form-control" %>

						<label for="text3">郵便番号:</label>
						<%= f.text_field :other_post_code, class: "form-control" %>

						<label for="text3">住所:</label>
						<%= f.text_field :other_address, class: "form-control" %>

					</label>
					

					
				</div>




			</div>
		</div>
		<br>

		<%= f.submit "購入確認ページへ", class: "btn btn-success btn-lg btn-block" %>

	<% end %>

</div>

app/views/orders/show.html.erb
<div class="container">
	<div class="row">
		<!-- カートのテーブル部分 -->
		<div class="col-md-9">
			<h1>カート</h1>
			<table class="table">

				<!-- テーブルのサイズ設定 -->
				<colgroup span="1" width="20%"></colgroup> <!-- 画像のカラム -->
				<colgroup span="1" width="20%"></colgroup> <!-- 削除ボタンのカラム -->
				<colgroup span="1" width="20%"></colgroup> <!-- 商品名のカラム -->
				<colgroup span="1" width="20%"></colgroup> <!-- 価格のカラム -->
				<colgroup span="1" width="20%"></colgroup> <!-- 数量のカラム -->

				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
						<th>価格</th>
						<th>数量</th>
					</tr>	
				</thead>

				<tbody>
					<% @carts.each do |cart| %>
						<tr>
							
							<td><%= attachment_image_tag cart.good, :jacket_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %></td>
							<td>
							</td>
							<td><%= cart.good.goods_title %></td>
							<td><%= cart.good.price %>円</td>
							<td>
								<%= cart.cart_value %>
							</td>
							
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>

		<!-- カートの合計金額、購入ボタン部分 -->
		<div class="col-md-3">
			<br>
			<br>
			<div class="card">
				<div class="card-body text-left">
					<h4>総計価格</h4>
				</div>
				<div class="card-body">
					<p class="text-left">合計価格:</p>
					<p class="text-right">¥<%= @price %>円</p>
					<p class="text-left">送料:</p>
					<p class="text-right">¥<%= @delivery_price %>円</p>
					<p class="text-left">消費税:</p>
					<p class="text-right">¥<%= @tax.to_i %>円</p>
					<hr>
					<p class="text-left">総計:</p>
					<p class="text-right">¥<%= @total_price.to_i %>円</p>
					<%= link_to "購入", home_finish_path, class: "btn btn-success btn-lg btn-block" %>
				</div>
			</div>
		</div>
	</div>
	<br>

	<!-- 住所表示部分 -->
	<div class="card">
		<div class="card-body">
			<h3 class="text-left">配送先</h3>
			<p class="text-left">〒<%= @post_code.chars[0] + @post_code.chars[1] + @post_code.chars[2] + "-" + @post_code.chars[3] + @post_code.chars[4] + @post_code.chars[5] + @post_code.chars[6] %></p>
			<p class="text-center"><%= @address %></p>
			
		</div>
	</div>
	<br>
	<div class="d-flex justify-content-end">
		<%= link_to "購入キャンセル", order_path(@orders.id), method: :delete, class:"btn btn-warning",data: {confirm:"カートの中身を消します。本当にいいの？"} %>
		<!-- ボタンとボタンのマージン用。消さないで -->
		<a>　</a>
		<%= link_to "前の画面に戻る", orders_path, class: "btn btn-info btn-sm" %>
	</div>
</div>