config/routes.rb
Rails.application.routes.draw do
  #作ったコントローラを呼び出す
  devise_for :users, :controllers =>{ 
       :registrations => 'users/registrations',
       :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :destroy, :update]
  resources :goods, only: [:index, :show]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :create, :show, :destroy, :new]

  get "/" => "home#top"
  get "home/finish" => "home#finish"
  get "home/done" => "home#done"


  
  
  get "admin/users" => "users#admin"
  get "admin/" => "users#admin_index"
  get "admin/users/:id" => "users#admin_show", as: "show_admin_user"
  delete "admin/users/:id" => "users#admin_destroy", as: "destroy_admin_user"
  get "admin/users/:id/edit" => "users#admin_edit", as: "edit_admin_user"
  patch "admin/users/:id" => "users#admin_update", as: "update_admin_user"

  get "admin/goods/" => "goods#admin_index"
  get "admin/goods/new" => "goods#admin_new"
  post "search" => "goods#search"
  get "admin/goods/:id" => "goods#admin_show", as: "show_admin_good"
  get "admin/goods/:id/edit" => "goods#admin_edit", as: "edit_admin_good"
  post "admin/goods/" => "goods#admin_create", as: "create_admin_good"
  delete "admin/goods/:id" => "goods#admin_destroy", as: "destroy_admin_good"
  patch "admin/goods/:id" => "goods#admin_update", as: "update_admin_good"

  get "admin/orders/:id/edit" => "orders#admin_edit", as: "edit_admin_order"
  patch "admin/orders/:id" => "orders#admin_update", as: "update_admin_order"

=begin
Prefix Verb   URI Pattern                                                                              Controller#Action
         new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
             user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
     destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
        new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
       edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
            user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
                          PUT    /users/password(.:format)                                                                devise/passwords#update
                          POST   /users/password(.:format)                                                                devise/passwords#create
 cancel_user_registration GET    /users/cancel(.:format)                                                                  users/registrations#cancel
    new_user_registration GET    /users/sign_up(.:format)                                                                 users/registrations#new
   edit_user_registration GET    /users/edit(.:format)                                                                    users/registrations#edit
        user_registration PATCH  /users(.:format)                                                                         users/registrations#update
                          PUT    /users(.:format)                                                                         users/registrations#update
                          DELETE /users(.:format)                                                                         users/registrations#destroy
                          POST   /users(.:format)                                                                         users/registrations#create
                edit_user GET    /users/:id/edit(.:format)                                                                users#edit
                     user GET    /users/:id(.:format)                                                                     users#show
                          PATCH  /users/:id(.:format)                                                                     users#update
                          PUT    /users/:id(.:format)                                                                     users#update
                          DELETE /users/:id(.:format)                                                                     users#destroy
                    goods GET    /goods(.:format)                                                                         goods#index
                     good GET    /goods/:id(.:format)                                                                     goods#show
                    carts GET    /carts(.:format)                                                                         carts#index
                          POST   /carts(.:format)                                                                         carts#create
                     cart PATCH  /carts/:id(.:format)                                                                     carts#update
                          PUT    /carts/:id(.:format)                                                                     carts#update
                          DELETE /carts/:id(.:format)                                                                     carts#destroy
                   orders GET    /orders(.:format)                                                                        orders#index
                          POST   /orders(.:format)                                                                        orders#create
                new_order GET    /orders/new(.:format)                                                                    orders#new
                    order GET    /orders/:id(.:format)                                                                    orders#show
                          DELETE /orders/:id(.:format)                                                                    orders#destroy
                          GET    /                                                                                        home#top
                home_done GET    /home/done(.:format)                                                                     home#done
              admin_users GET    /admin/users(.:format)                                                                   users#admin
                    admin GET    /admin(.:format)                                                                         users#admin_index
          show_admin_user GET    /admin/users/:id(.:format)                                                               users#admin_show
       destroy_admin_user DELETE /admin/users/:id(.:format)                                                               users#admin_destroy
          edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          users#admin_edit
        update_admin_user PATCH  /admin/users/:id(.:format)                                                               users#admin_update
              admin_goods GET    /admin/goods(.:format)                                                                   goods#admin_index
          admin_goods_new GET    /admin/goods/new(.:format)                                                               goods#admin_new
                   search POST   /search(.:format)                                                                        goods#search
          show_admin_good GET    /admin/goods/:id(.:format)                                                               goods#admin_show
          edit_admin_good GET    /admin/goods/:id/edit(.:format)                                                          goods#admin_edit
        create_admin_good POST   /admin/goods(.:format)                                                                   goods#admin_create
       destroy_admin_good DELETE /admin/goods/:id(.:format)                                                               goods#admin_destroy
        update_admin_good PATCH  /admin/goods/:id(.:format)                                                               goods#admin_update
         edit_admin_order GET    /admin/orders/:id/edit(.:format)                                                         orders#admin_edit
       update_admin_order PATCH  /admin/orders/:id(.:format)                                                              orders#admin_update
               refile_app        /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
       rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
=end

end

app/models/good.rb
class Good < ApplicationRecord
	has_many :music_titles, dependent: :destroy
	has_many :carts
	attachment :jacket_image
	has_many :orders_children

	accepts_nested_attributes_for :music_titles, allow_destroy: true
	accepts_nested_attributes_for :carts, :orders_children

	validates :price, presence: true, format: { with: /\A[0-9]+\Z/ }
	validates :artist, :goods_title, :rabel, :stock, presence: true
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController

  before_action :admin_flag_check?, only: [:admin_index, :admin_show, :admin_new, :admin_create, :admin_destroy, :admin_update, :admin_edit]
  before_action :resignation_flag_check?, only:[:admin_index, :admin_show, :admin_new, :admin_create, :admin_destroy, :admin_edit, :admin_update]

  def index
    @goods = Good.all
    @good = Good.new

  end

  def search
    @search = Good.new(search_params)
    @goods = Good.where(goods_title: @search.goods_title)
    @good = Good.new
    render "index"
  end

  def show
    @good = Good.find(params[:id])
    @music_titles = MusicTitle.where(good_id: @good.id)
    @cart = Cart.new
  end

  def admin_index
    @goods = Good.all
  end

  def admin_show
    @good = Good.find(params[:id])
    @music_titles = MusicTitle.where(good_id: @good.id)

    if @good.goods_status == "1"
      @status = "販売停止中"
    else
      @status = "販売中"
    end
  end

  def admin_new
    @goods = Good.new
    @goods.music_titles.build
  end

  def admin_create
    good = Good.new(good_params)

    # 曲順をセット
    song_number_set(good)

    if good.save
    # 商品一覧ページにて戻す
      redirect_to admin_goods_path
    else
      redirect_to admin_goods_path
    end
  end

  def admin_destroy
    @good = Good.find(params[:id])
    # グッズを単純に消すと、注文履歴との不整合が発生するので、
    # グッズ削除フラグを立てて、各ビューで表示しないように制御する。
    @good.good_delete_flag = 1
    @good.save
    redirect_to admin_goods_path
  end

  def admin_edit
    @good = Good.find(params[:id])
    @music_titles = MusicTitle.where(good_id: @good.id)

  end

  def admin_update
    good = Good.find(params[:id])
    if good.update(good_params)

      # グッズの中身を入れ替える
      # 曲順を入れる処理をする関数に@goodを渡す
      song_number_set(good)

      # saveに成功した場合は、商品一覧ページに遷移させる
      if good.save
        redirect_to admin_goods_path

      # saveに失敗した場合は、編集画面に戻す
      else
        @good = good
        render "admin_edit"
      end
    
    # updateに失敗した場合は、編集画面に戻す
    else
      @good = good
      render "admin_edit"
    end
  end

  # 曲順を入れる関数 引数:Good（単数）を入れると、曲順を1から設定します。
  def song_number_set(good)
    song_number = 1
    good.music_titles.each do |music|
      music.song_number = song_number
      song_number = song_number + 1
    end
  end

  # ストロングパラメーター
  private
  def good_params
    # モデルの複数形_attributes
    params.require(:good).permit(:id, :artist, :goods_status, :goods_title, :jacket_image, :price, :rabel, :stock, music_titles_attributes:[:id, :song, :_destroy])
  end

  def search_params
    params.require(:good).permit(:goods_title)
  end


end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/admin_edit.html.erb
<div class="containar">
  <%= form_for @good, url: update_admin_good_path do |f| %>
  <div class="row">
    
      <div class="col-md-2">
        <div class="d-flex justify-content-center">
          <p>アーティスト名</p>
        </div>
      </div>
      <div class="col-md-10">
        <%= f.text_field :artist %>
      </div>

      <div class="col-md-2">
        <div class="d-flex justify-content-center">
          <p>シングル・アルバム名</p>
        </div>
      </div>
      <div class="col-md-10">
        <%= f.text_field :goods_title %>
      </div>

      <div class="col-md-2">
        <div class="d-flex justify-content-center">
          <p>ジャケット画像</p>
        </div>
      </div>
      <div class="col-md-10">
        <%= f.attachment_field :jacket_image %>
      </div>

      <div class="col-md-2">
        <div class="d-flex justify-content-center">
          <p>価格（税別価格）</p>
        </div>
      </div>
      <div class="col-md-10">
        <%= f.text_field :price %>
      </div>

      <div class="col-md-2">
        <div class="d-flex justify-content-center">
          <p>レーベル名</p>
        </div>
      </div>
      <div class="col-md-10">
        <%= f.text_field :rabel %>

      </div>

  <div class="col-md-2">
    <div class="d-flex justify-content-center">
      <p>ジャンル</p>
    </div>
  </div>
  <div class="col-md-10">
    <%= f.text_field :type %>
  </div>
  </div>

  <%= f.nested_fields_for :music_titles, wrapper_tag: :div do |music| %>
  <div class="row">
      <div class="col-md-2">
        <div class="d-flex justify-content-center">
          <p>ディスク内の曲</p>
        </div>
      </div>
      <div class="col-md-10">
        <%= music.text_field :song %>
      　<div class="d-flex justify-content-center">
        <%= music.remove_nested_fields_link '削除', class: "btn btn-primary", role: 'button' %>
      　</div>
      </div>
    </div>
  <% end %>
  <%= f.add_nested_fields_link :music_titles, '曲を追加', class: "btn btn-info", role: 'button' %>

 
    

  <br>

  <div class="row">
    <div class="col-md-2">
      <div class="d-flex justify-content-center">
        <p>在庫数</p>
      </div>
    </div>
    <div class="col-md-10">
      <%= f.text_field :stock %>
    </div>
    <div class="col-md-2">
      <div class="d-flex justify-content-center">
        <p>ステータス</p>
      </div>
    </div>
    <div class="col-sm-3 btn-group" data-toggle="buttons">
      <label class="btn btn-outline-secondary active" style="width:50%">
        <%= f.radio_button :goods_status, 0 %> 販売中
      </label>
      <label class="btn btn-outline-secondary" style="width:50%">
        <%= f.radio_button :goods_status, 1 %> 販売中止中
      </label>
    </div>
  </div>
  <%= f.submit "更新", class: "btn btn-primary btn-block" %>

  <% end %>
</div>

app/views/goods/admin_index.html.erb
<div class="title">
	<h1>商品一覧</h1>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<table class="table">
				<thead>
					<colgroup span="1" style="width:10%;">
					<colgroup span="2" style="width:20%;">
					<colgroup span="1" style="width:10%;">

				<div class="row">
						<th></th>
						<th>アーティスト名</th>
						<th>シングル/アルバム名</th>
						<th>販売状況</th>
				</div>
					
				</thead>
				
				<tbody>
				<% @goods.each do |good| %>
				
					<!-- goodテーブルにgood_delete_flagが立っていたら、表示しない -->
					<% if good.good_delete_flag == 1 %>
						<!-- 表示をしない -->
					<% else %>
						<tr>
							<td><a href="<%= "/admin/goods/#{good.id}" %>"><%= attachment_image_tag good, :jacket_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %></a></td>
							<td><%= good.artist %></td>
							<td><%= good.goods_title %></td>
							<% if good.goods_status == "1" %>
							<td><p>販売停止中</p></td>
							<% else %>
							<td><p>販売中</p></td>
							<% end %>
						</tr>
					<% end %>
					
				<% end %>
				</tbody>
			</table>
		</div>
		
 		<%= link_to "戻る", admin_users_path, class: "btn btn-primary mx-auto" %>
 		
	</div>
</div>
 

app/views/goods/admin_new.html.erb
<div class="containar">
  <%= form_for @goods, url: create_admin_good_path do |f| %>
  <div class="row">
    
    	<div class="col-md-2">
    		<div class="d-flex justify-content-center">
    			<p>アーティスト名</p>
    		</div>
    	</div>
    	<div class="col-md-10">
        <%= f.text_field :artist %>
    	</div>

    	<div class="col-md-2">
    		<div class="d-flex justify-content-center">
    			<p>シングル・アルバム名</p>
    		</div>
    	</div>
    	<div class="col-md-10">
        <%= f.text_field :goods_title %>
    	</div>

    	<div class="col-md-2">
    		<div class="d-flex justify-content-center">
    			<p>ジャケット画像</p>
    		</div>
    	</div>
    	<div class="col-md-10">
        <%= f.attachment_field :jacket_image %>
    	</div>

    	<div class="col-md-2">
    		<div class="d-flex justify-content-center">
    			<p>価格（税別価格）</p>
    		</div>
    	</div>
    	<div class="col-md-10">
        <%= f.text_field :price %>
    	</div>

    	<div class="col-md-2">
    		<div class="d-flex justify-content-center">
    			<p>レーベル名</p>
    		</div>
    	</div>
    	<div class="col-md-10">
        <%= f.text_field :rabel %>
    	</div>
    
  </div>


  <%= f.nested_fields_for :music_titles, wrapper_tag: :div do |music| %>
  <div class="row">
      <div class="col-md-2">
        <div class="d-flex justify-content-center">
          <p>ディスク内の曲</p>
        </div>
      </div>
      <div class="col-md-10">
        <%= music.text_field :song %>
      　<div class="d-flex justify-content-center">
        <%= music.remove_nested_fields_link '削除', class: "btn btn-primary", role: 'button' %>
      　</div>
      </div>
    </div>
  <% end %>
  <%= f.add_nested_fields_link :music_titles, '曲を追加', class: "btn btn-info", role: 'button' %>

  <br>

  <div class="row">
  	<div class="col-md-2">
  		<div class="d-flex justify-content-center">
  			<p>在庫数</p>
  		</div>
  	</div>
  	<div class="col-md-10">
      <%= f.text_field :stock %>
  	</div>
  </div>
  <%= f.submit "更新", class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/goods/admin_show.html.erb
<div class="container">
	<h2>商品詳細</h2>

	<div class="row">
		<!-- ジェケット画像表示させる所 -->
		<div class="col-md-4">
				<div class="card">
					<div class="card-body text-center">
						<%= attachment_image_tag @good, :jacket_image, format: "jpeg", fallback: "no_image.jpg", size: "300x300" %>
					</div>
				</div>
		</div>
		<!-- 商品名とかを表示させる所 -->
		<div class="col-md-8">
			<div class="card">
				<div class="card-body text-center">
					<!--商品タイトル -->
					<%= "タイトル:　" + @good.goods_title %>
				</div>
			</div>

			<br>

			<div class="card">
				<div class="card-body text-center">
					<!-- アーティスト名 -->
					<%= "アーティスト名:　" + @good.artist %>
				</div>
			</div>

			<br>

			<div class="card">
				<div class="card-body text-center">
				  <% if @good.stock == 0 %>
				   <p>在庫なし</p>
				   <% else %>
				   <p>在庫あり</p>
				   <% end %>
				</div>
			</div>

		</div>
	</div>

	<br>

	<div class="card">
		<div class="card-body">
			<h3>商品説明</h3>


			<p>CD: 1枚目</p>
			<% @music_titles.each do |title| %>
				<p  style="line-height: 6px"><%= title.song_number.to_s + "曲目:　" + title.song %></p>
			<% end %>
		</div>
	</div>

	<br>

    <div class="d-flex justify-content-end">
    	<div class="b" style="border:solid 1px; height: 30px; width: 300px;">
    		<p style="text-align: center; line-height: 30px;"> <%= @good.price %>円</p>
    	</div>
    </div>
    <br>
    <div class="d-flex justify-content-end">
    	<div class="b" style="border:solid 1px; height: 30px; width: 300px;">
    		<p style="text-align: center; line-height: 30px;"><%= "在庫数:　" + @good.stock.to_s %></p>
    	</div>
    </div>
    <br>
    <div class="d-flex justify-content-end">
        <div class="b" style="border:solid 1px; height: 30px; width: 300px;">
    		<p style="text-align: center; line-height: 30px;"> 現ステータス: <%= @status %></p>
    	</div>
    </div>
    <br>

    <div class="d-flex justify-content-end">
      <div class="mx-2">
      <%= link_to "編集", edit_admin_good_path(@good.id), class:"btn btn-success" %>
     </div>
     <div class="mx-2">
      <%= link_to "削除", destroy_admin_good_path(@good.id), method: :delete, class:"btn btn-success",data: {confirm:"削除しますか？"}
      %>
     </div>
     <div class="mx-2">
      <%= link_to "戻る", admin_goods_path, class:"btn btn-success" %>
     </div>
    </div>


</div>

app/views/goods/index.html.erb
<%= flash[:notice] %>
<div class="clearfix">
<div class="container">
  <div class="row">
    <%= form_for @good, url: search_path do |f| %>
    <%= f.text_field :goods_title %>
    <%= f.submit "検索" %>
    <% end %>
  </div>
  <% @goods.each do |good| %>

    <!-- goodテーブルにgood_delete_flagが立っていたら、表示しない -->
    <% if good.good_delete_flag == 1 %>
      <!-- 表示をしない -->
    <% else %>

      <div class="card" style= "margin: 20px; width: 21%; float: left;">
        <table class= "table table-hover">
          <thead></thead>
          <tbody>
            <tr align="center">
            <td><a href="<%= "/goods/#{good.id}" %>"><%= attachment_image_tag good, :jacket_image, format: "jpeg", fallback: "no_image.jpg", size: "200x200" %></a></td>
            </tr>
            <tr align="center">
            <td><%= good.goods_title.slice(0..23) %></td>
            </tr>
            <tr align="center">
              <td><%= good.artist.slice(0..23) %></td>
            </tr>
            <tr align="center">
              <td><%= good.price %>円</td>
            </tr>
            <tr align="center">
              <td>在庫あり</td>
            </tr>
          </tbody>
        </table>
      </div>

    <% end %>

  <% end %>
</div>
</div>

app/views/goods/show.html.erb
<div class="container">
	<h2>商品詳細</h2>

	<div class="row">
		<!-- ジェケット画像表示させる所 -->
		<div class="col-md-4">
				<div class="card">
					<div class="card-body text-center">
						<%= attachment_image_tag @good, :jacket_image, format: "jpeg", fallback: "no_image.jpg", size: "300x300" %>
					</div>
				</div>
		</div>
		<!-- 商品名とかを表示させる所 -->
		<div class="col-md-8">
			<div class="card">
				<div class="card-body text-center">
					<%= @good.goods_title %>
				</div>
			</div>

			<br>

			<div class="card">
				<div class="card-body text-center">
					<%= @good.artist %>
				</div>
			</div>

			<br>

			<div class="card">
				<div class="card-body text-center">
					<%= @good.price %>円
				</div>
			</div>

			<br>

			<div class="card">
				<div class="card-body text-center">
					<% if @good.stock == 0 %>
				   <p>在庫なし</p>
				   <% else %>
				   <p>在庫あり</p>
				   <% end %>
				</div>
			</div>

		</div>
	</div>

	<br>

	<div class="card">
		<div class="card-body">
			<h3>商品説明</h3>

			<p>CD: 1枚目</p>
			<% @music_titles.each do |title| %>
			<p  style="line-height: 6px"><%= title.song_number.to_s + "曲目:  " + title.song %></p>
			<% end %>
		</div>
	</div>

	<br>

	<!-- 商品説明部分 -->
	<%= form_for @cart, url: carts_path do |cart| %>
		<div class="row">
			<div class="col-md-5">
				<div class="card">
					<div class="card-body">
						<div class="form-group row">
						    <label for="text3a" class="col-sm-2 col-form-label">個数</label>
						    <div class="col-sm-7">
						     <%= cart.number_field :cart_value, min: 1, :value => 1 %>
						     <%= cart.hidden_field :good_id, :value => @good.id  %>
						    </div>
						    <div class="col-sm-3">
						    	<p>個</p>
						    </div>
					  	</div>
					</div>
				</div>
			</div>
		<!-- 左の余白作る用。 -->
		<div class="col-md-7">
		</div>
	</div>
	<br>

	<!-- 2つのボタンを中央揃えにする。 -->
	<div class="row">
		<div class="col-md-6">
			<%= cart.submit "カートに追加", class: "btn btn-warning btn-lg btn-block" %>
		</div>

		<div class="col-md-6">
			<button type="button" class="btn btn-primary btn-lg btn-block">戻る</button>
		</div>
	</div>
	<% end %>

</div>